Table "model.integration_tests.verify_get_table_alias"{
            "actual" varchar
"expected" varchar
        }

        Table "model.integration_tests.verify_if_column_value_to_match_regex"{
            "text_only" varchar
"number_only" varchar
        }

        Table "model.integration_tests.verify_materialized_view"{
            "time_key" varchar
"time_value" varchar
        }

        Table "model.integration_tests.verify_money_to_words_en"{
            "input" varchar
"expected" varchar
"actual" varchar
        }

        Table "model.integration_tests.verify_generate_schema_name"{
            "actual" varchar
"expected" varchar
        }

        Table "model.integration_tests.verify_datepart"{
            "input" varchar
"date_part" varchar
"actual" varchar
"expected" varchar
        }

        Table "model.integration_tests.verify_get_base_times_hour"{
            "time_value" varchar
        }

        Table "model.integration_tests.verify_get_base_times_minute"{
            "time_value" varchar
        }

        Table "model.integration_tests.verify_get_base_times_second"{
            "N" varchar
"value" varchar
"time_value" varchar
        }

        Table "model.integration_tests.verify_get_time_dimension_hour"{
            "time_value" varchar
"time_string" varchar
"time24_string" varchar
"hour_number" varchar
"hour_name" varchar
"hour24_number" varchar
"hour24_name" varchar
"time_key" varchar
        }

        Table "model.integration_tests.verify_get_time_dimension_minute"{
            "time_value" varchar
"time_string" varchar
"time24_string" varchar
"hour_number" varchar
"hour_name" varchar
"hour24_number" varchar
"hour24_name" varchar
"minute_number" varchar
"hour_minute_name" varchar
"hour24_minute_name" varchar
"time_key" varchar
        }

        Table "model.integration_tests.verify_get_time_dimension_second"{
            "time_value" varchar
"time_string" varchar
"time24_string" varchar
"hour_number" varchar
"hour_name" varchar
"hour24_number" varchar
"hour24_name" varchar
"minute_number" varchar
"hour_minute_name" varchar
"hour24_minute_name" varchar
"second_number" varchar
"time_key" varchar
        }

        Table "model.integration_tests.verify_get_time_key"{
            "input" varchar
"actual" varchar
"expected" varchar
        }

        Table "model.integration_tests.verify_str_to_date"{
            "expected" varchar
"yyyymmdd" varchar
"invalid" varchar
"mm/dd/yy" varchar
"yy.mm.dd" varchar
"dd/mm/yy" varchar
"dd.mm.yy" varchar
"dd-mm-yy" varchar
"dd-Mon-yy" varchar
"Mon dd, yy" varchar
"mm-dd-yy" varchar
"yy/mm/dd" varchar
"yymmdd" varchar
"yyyy-mm-dd" varchar
"mm/dd/yyyy" varchar
"yyyy.mm.dd" varchar
"dd/mm/yyyy" varchar
"dd.mm.yyyy" varchar
"dd-mm-yyyy" varchar
"dd Mon yyyy" varchar
"Mon dd, yyyy" varchar
"mm-dd-yyyy" varchar
"yyyy/mm/dd" varchar
"actual" varchar
        }

        Table "model.dbt_resto.dim_box"{
            "box_key" varchar
        }

        Table "model.dbt_resto.dim_date"{
            "date_key" varchar
"box_day" varchar
"box_week" varchar
"box_month" varchar
"box_month_name" varchar
"box_year" varchar
        }

        Table "model.dbt_resto.dim_prize"{
            "prize_key" varchar
"prize_order" varchar
        }

        Table "model.dbt_resto.fact_number"{
            "number_value" varchar
"occurrence" varchar
"occurrence_pos_1" varchar
"occurrence_pos_2" varchar
"occurrence_pos_3" varchar
"occurrence_pos_4" varchar
"occurrence_pos_5" varchar
"occurrence_pos_6" varchar
"occurrence_pos_7" varchar
"last_appearance" varchar
"last_appearance_pos_1" varchar
"last_appearance_pos_2" varchar
"last_appearance_pos_3" varchar
"last_appearance_pos_4" varchar
"last_appearance_pos_5" varchar
"last_appearance_pos_6" varchar
"last_appearance_pos_7" varchar
        }

        Table "model.dbt_resto.fact_result"{
            "fact_result_key" varchar
"box_key" varchar
"prize_key" varchar
"date_key" varchar
"no_of_won" varchar
"prize_value" varchar
"prize_paid" varchar
"is_prize_taken" varchar
        }

        Table "model.dbt_resto.fact_set_number"{
            "occurrence" varchar
"last_appearance" varchar
        }

        Table "model.dbt_resto.staging_power655_box"{
            "sk_box" varchar
"box_date" varchar
        }

        Table "model.dbt_resto.staging_power655_box_detail"{
            "sk_box_detail" varchar
"prize_name" varchar
        }

        Table "model.dbt_resto.fact_number_forecast"{
            "number_value" varchar
"rn" varchar
"forecast_numbers" varchar
"forecast_1" varchar
"forecast_2" varchar
"forecast_3" varchar
"forecast_4" varchar
"forecast_5" varchar
"forecast_6" varchar
"forecasting.forecast_date" varchar
"last_box_date" varchar
"last_box_result_numbers" varchar
"last_box_result_number_1" varchar
"last_box_result_number_2" varchar
"last_box_result_number_3" varchar
"last_box_result_number_4" varchar
"last_box_result_number_5" varchar
"last_box_result_number_6" varchar
        }

        Table "model.dbt_resto.fact_number_scoring"{
            "no" varchar
"weight" varchar
"weight_1" varchar
"weight_2" varchar
"weight_3" varchar
"weight_4" varchar
"weight_5" varchar
"weight_6" varchar
"score_1" varchar
"score_2" varchar
"score_3" varchar
"score_4" varchar
"score_5" varchar
"score_6" varchar
"rank_pos_1" varchar
"rank_pos_2" varchar
"rank_pos_3" varchar
"rank_pos_4" varchar
"rank_pos_5" varchar
"rank_pos_6" varchar
"fact_key" varchar
"forecast_date" varchar
        }

        Ref: "model.dbt_resto.fact_number"."last_appearance" > "model.dbt_resto.dim_date"."date_key"
        Ref: "model.dbt_resto.fact_number"."last_appearance_pos_1" > "model.dbt_resto.dim_date"."date_key"
        Ref: "model.dbt_resto.fact_number"."last_appearance_pos_2" > "model.dbt_resto.dim_date"."date_key"
        Ref: "model.dbt_resto.fact_number"."last_appearance_pos_3" > "model.dbt_resto.dim_date"."date_key"
        Ref: "model.dbt_resto.fact_number"."last_appearance_pos_4" > "model.dbt_resto.dim_date"."date_key"
        Ref: "model.dbt_resto.fact_number"."last_appearance_pos_5" > "model.dbt_resto.dim_date"."date_key"
        Ref: "model.dbt_resto.fact_number"."last_appearance_pos_6" > "model.dbt_resto.dim_date"."date_key"
        Ref: "model.dbt_resto.fact_result"."box_key" > "model.dbt_resto.dim_box"."box_key"
        Ref: "model.dbt_resto.fact_result"."prize_key" > "model.dbt_resto.dim_prize"."prize_key"
        Ref: "model.dbt_resto.fact_result"."date_key" > "model.dbt_resto.dim_date"."date_key"
        