from dataclasses import dataclass
import json
from unittest import mock

import pytest

from dbterd.adapters.targets.drawdb import DrawdbAdapter
from dbterd.core.models import Column, Ref, Table


@dataclass
class DummyManifestMetadata:
    generated_at: str


@dataclass
class DummyManifest:
    metadata: DummyManifestMetadata


class TestDrawdbTestRelationship:
    @pytest.mark.parametrize(
        "tables, relationships, select, exclude, resource_type, omit_entity_name_quotes, expected",
        [
            (
                [
                    Table(
                        name="model.dbt_resto.table1",
                        node_name="model.dbt_resto.table1",
                        database="--database--",
                        schema="--schema--",
                        columns=[
                            Column(
                                name="name1",
                                data_type="--name1-type--",
                                description="column name 1",
                            )
                        ],
                        raw_sql="--irrelevant--",
                    ),
                ],
                [],
                [],
                [],
                ["model"],
                False,
                json.dumps(
                    {
                        "author": "dbterd",
                        "title": "Generated by dbterd",
                        "date": "dummy",
                        "tables": [
                            {
                                "id": 0,
                                "name": "model.dbt_resto.table1",
                                "x": 0,
                                "y": 0,
                                "comment": "",
                                "indices": [],
                                "color": "#175e7a",
                                "fields": [
                                    {
                                        "id": 0,
                                        "name": "name1",
                                        "type": "--name1-type--",
                                        "default": "",
                                        "check": "",
                                        "primary": False,
                                        "unique": False,
                                        "notNull": False,
                                        "increment": False,
                                        "comment": "column name 1",
                                    },
                                ],
                            }
                        ],
                        "relationships": [],
                        "notes": [],
                        "subjectAreas": [],
                        "database": "generic",
                        "types": [],
                    }
                ),
            ),
            (
                [
                    Table(
                        name="model.dbt_resto.table1",
                        node_name="model.dbt_resto.table1",
                        database="--database--",
                        schema="--schema--",
                        columns=[Column(name="name1", data_type="--name1-type--")],
                        raw_sql="--irrelevant--",
                    ),
                    Table(
                        name="model.dbt_resto.table2",
                        node_name="model.dbt_resto.table2",
                        database="--database2--",
                        schema="--schema2--",
                        columns=[Column(name="name2", data_type="--name2-type2--")],
                        raw_sql="--irrelevant--",
                    ),
                ],
                [
                    Ref(
                        name="test.dbt_resto.relationships_table1",
                        table_map=["model.dbt_resto.table2", "model.dbt_resto.table1"],
                        column_map=["name2", "name1"],
                    )
                ],
                [],
                [],
                ["model", "source"],
                False,
                json.dumps(
                    {
                        "author": "dbterd",
                        "title": "Generated by dbterd",
                        "date": "dummy",
                        "tables": [
                            {
                                "id": 0,
                                "name": "model.dbt_resto.table1",
                                "x": 0,
                                "y": 0,
                                "comment": "",
                                "indices": [],
                                "color": "#175e7a",
                                "fields": [
                                    {
                                        "id": 0,
                                        "name": "name1",
                                        "type": "--name1-type--",
                                        "default": "",
                                        "check": "",
                                        "primary": False,
                                        "unique": False,
                                        "notNull": False,
                                        "increment": False,
                                        "comment": "",
                                    }
                                ],
                            },
                            {
                                "id": 1,
                                "name": "model.dbt_resto.table2",
                                "x": 500,
                                "y": 0,
                                "comment": "",
                                "indices": [],
                                "color": "#175e7a",
                                "fields": [
                                    {
                                        "id": 0,
                                        "name": "name2",
                                        "type": "--name2-type2--",
                                        "default": "",
                                        "check": "",
                                        "primary": False,
                                        "unique": False,
                                        "notNull": False,
                                        "increment": False,
                                        "comment": "",
                                    }
                                ],
                            },
                        ],
                        "relationships": [
                            {
                                "id": 0,
                                "name": "fk__model.dbt_resto.table1_model.dbt_resto.table2__name1",
                                "cardinality": "Many to one",
                                "startTableId": 0,
                                "endTableId": 1,
                                "startFieldId": 0,
                                "endFieldId": 0,
                                "updateConstraint": "No action",
                                "deleteConstraint": "No action",
                            }
                        ],
                        "notes": [],
                        "subjectAreas": [],
                        "database": "generic",
                        "types": [],
                    }
                ),
            ),
        ],
    )
    def test_build_erd(
        self,
        tables,
        relationships,
        select,
        exclude,
        resource_type,
        omit_entity_name_quotes,
        expected,
    ):
        adapter = DrawdbAdapter()
        drawdb = adapter.build_erd(
            tables=tables,
            relationships=relationships,
            manifest=DummyManifest(metadata=DummyManifestMetadata(generated_at="dummy")),
            omit_entity_name_quotes=omit_entity_name_quotes,
        )
        assert json.loads(drawdb) == json.loads(expected)

    def test_get_y(self):
        adapter = DrawdbAdapter()
        tables = [
            Table(
                name="model.dbt_resto.table1",
                node_name="--irrelevant--",
                database="--database--",
                schema="--schema--",
                columns=[Column(name="name1", data_type="--name1-type--")],
                raw_sql="--irrelevant--",
            ),
            Table(
                name="model.dbt_resto.table2",
                node_name="--irrelevant--",
                database="--irrelevant--",
                schema="--irrelevant--",
                columns=[Column(name="--irrelevant--", data_type="--irrelevant--")],
                raw_sql="--irrelevant--",
            ),
            Table(
                name="model.dbt_resto.table3",
                node_name="--irrelevant--",
                database="--irrelevant--",
                schema="--irrelevant--",
                columns=[Column(name="--irrelevant--", data_type="--irrelevant--")],
                raw_sql="--irrelevant--",
            ),
            Table(
                name="model.dbt_resto.table4",
                node_name="--irrelevant--",
                database="--irrelevant--",
                schema="--irrelevant--",
                columns=[Column(name="--irrelevant--", data_type="--irrelevant--")],
                raw_sql="--irrelevant--",
            ),
            Table(
                name="model.dbt_resto.table5",
                node_name="--irrelevant--",
                database="--irrelevant--",
                schema="--irrelevant--",
                columns=[Column(name="--irrelevant--", data_type="--irrelevant--")],
                raw_sql="--irrelevant--",
            ),
        ]
        assert adapter.get_y(tables, 0, {}) == 0
        assert adapter.get_y(tables, 1, {}) == 0
        assert adapter.get_y(tables, 2, {}) == 0
        assert adapter.get_y(tables, 3, {}) == 0
        assert adapter.get_y(tables, 4, {"model.dbt_resto.table1": {"y": 0}}) == 100
        assert adapter.get_y(tables, 4, {"model.dbt_resto.table1": {"y": 5}}) == 100 + 5

    def test_run(self):
        adapter = DrawdbAdapter()
        with mock.patch.object(DrawdbAdapter, "build_erd", return_value="dummy") as mock_build_erd:
            assert adapter.run(tables=[], relationships=[], output_file_name="xyz") == ("xyz", "dummy")
            assert adapter.run(tables=[], relationships=[]) == ("output.ddb", "dummy")
            assert mock_build_erd.call_count == 2

    def test_format_table(self):
        """Test format_table method returns JSON string."""
        adapter = DrawdbAdapter()
        table = Table(
            name="model.dbt_resto.table1",
            node_name="model.dbt_resto.table1",
            database="--database--",
            schema="--schema--",
            columns=[Column(name="name1", data_type="--name1-type--")],
            raw_sql="--irrelevant--",
        )
        graphic_tables = {"model.dbt_resto.table1": {"id": 0, "x": 0, "y": 0, "fields": {"name1": {"id": 0}}}}
        result = adapter.format_table(table, graphic_tables=graphic_tables, idx=0)
        parsed = json.loads(result)
        assert parsed["id"] == 0
        assert parsed["name"] == "model.dbt_resto.table1"

    def test_format_relationship(self):
        """Test format_relationship method returns JSON string."""
        adapter = DrawdbAdapter()
        relationship = Ref(
            name="test.dbt_resto.relationships_table1",
            table_map=["model.dbt_resto.table2", "model.dbt_resto.table1"],
            column_map=["name2", "name1"],
        )
        graphic_tables = {
            "model.dbt_resto.table1": {"id": 0, "x": 0, "y": 0, "fields": {"name1": {"id": 0}}},
            "model.dbt_resto.table2": {"id": 1, "x": 500, "y": 0, "fields": {"name2": {"id": 0}}},
        }
        result = adapter.format_relationship(relationship, graphic_tables=graphic_tables, idx=0)
        parsed = json.loads(result)
        assert parsed["id"] == 0
        assert parsed["cardinality"] == "Many to one"
